# Change these first
owner: VoisinsVigilants # Your GitHub organization or username, where this repository lives
repo: upptime_staging # The name of this repository

sites:
  - name: Site Voisins Vigilants et Solidaires (PROD)
    url: https://__app.voisinsvigilants.org
  - name: B2B - Voisins Vigilants Connect (Staging)
    url: https://__staging.voisinsvigilants-connect.org
  - name: Hodatis (Staging)
    url: https://staging.hodatis.com
  - name: Api B2C - Api Voisins Vigilants (Staging)
    url: __staging-api-flutter.voisinsvigilants.org
    check: "tcp-ping"
  - name: Data - Voisins Vigilants Data (Staging)
    url: https://__staging.voisinsvigilants-data.org/
  - name: Territoire - Territoire Vigilant (Staging)
    url: https://__staging.territoirevigilant.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: upptime_staging
  logoUrl: https://firebasestorage.googleapis.com/v0/b/voisins-vigilants.appspot.com/o/asset%2Flogo_vvs_vertical.svg?alt=media&token=b8b44c73-41e0-4584-bce2-c549b5585bcc
  name: Voisins Vigilants Staging
  introTitle: "**Voisins Vigilants Staging** environnement de Staging"
  introMessage: Page de status des applications de la société Voisins Vigilants et Solidaires®
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
